### ISSUE TITLE
Issue with the wall?

### ISSUE THREAD

**Issue by msbCyricTohoku** [TuturGabao/Game-Project#1]
maxis112 here, I will check the issue, please provide more information regarding that issue and I will check it once I get some free time! cheers!

**Comment by TuturGabao** [comment]
So if you go to the right so that the ennemy on the upper platform (named as centerRect in the code) cant be seen on the screen, this ennemy will fall on the lower platform . After some analysis i found that if the walls on the upper platform (named as centerRectLeft and centerRectRight) are shorter than the ennemy the issue will happen. However if the walls are taller than the ennemy then everything work perfectly

**Comment by msbCyricTohoku** [comment]
I have just now pushed my commit to the repo, please check if it has been solved. please let me know then.

**Comment by TuturGabao** [comment]
I will check tomorrow, i gotta sleep right now
